---
- name: create a temp dir for stress-ng to use
  file:
    path: "{{ stressng.stress_tmp_dir }}"
    state: directory

- name: run stress-ng
  command: >
    screen -S stress -d -m
    stress-ng
    --timeout {{ stressng.test_duration }}
    --hdd-bytes {{ stressng.bytes_per_hdd_worker }}
    --vm-bytes {{ stressng.bytes_per_vm_worker }}
    --vm-method all
    --cpu-method all
    --cpu {{ stressng.cpu_workers }}
    --vm {{ stressng.vm_workers }}
    --hdd {{ stressng.hdd_workers }}
    --log-file {{ stressng.stress_tmp_dir }}/stress-ng-{{ ansible_date_time.iso8601_basic_short }}.log
    ;
  args:
    chdir: "{{ stressng.stress_tmp_dir }}"
  tags: skip_ansible_lint

- name: Get stress-ng process count
  shell: ps -ef|grep "[s]tress-ng"|wc -l
  register: stress_procs
  changed_when: False
  check_mode: False
  tags: skip_ansible_lint

- name: Fail if no stress-ng processes found
  fail:
    msg: No stress-ng processes found!
  when: stress_procs.stdout|int < 1

- name: Get dead screen count
  shell: screen -ls|grep -c Dead
  register: reg_dead_screens
  changed_when: False
  check_mode: False
  failed_when: False
  tags: skip_ansible_lint

- name: Fail if there are dead screens
  fail:
    msg: Found dead screenstressng. stress-ng probably did not start. Run screen -wipe and try again.
  when: reg_dead_screens.stdout|int > 0