---

stressng:
    test_duration: "40"  # Test duration in seconds (defaults to 86400 which is 24h)
    cpu_workers: "1"
    methods: rand
    stress_tmp_dir: /home/testvnf/stress-tmp
    skip_screen_check: false