---

- hosts: all
  remote_user: testvnf
  vars_files:
    - /home/shubham/Desktop/P4/configure/config.yml
  become: yes

  roles:

  - { role: stress-ng,
      tags: stress-ng }
      
  - { role: collectd, 
      tags: collectd }