---

- hosts: all
  remote_user: testuser
  vars_files:
    - /home/shubham/Desktop/P4/configure/config.yml

  roles:

  - { role: stress-ng,
      tags: stress-ng }
      
  - { role: collectd, 
      tags: collectd }